// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed unreachable.png
var resourceUnreachablePngData []byte
var resourceUnreachablePng = &fyne.StaticResource{
	StaticName:    "unreachable.png",
	StaticContent: resourceUnreachablePngData,
}
